# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf8903622e8641b9a0963d84858409b3924b436c90d4a5cb77e9f0bf6bb5e2f0839cfea9e13855759dd55830c2128b7b9cc93778f9f76f6acd4f06a73619b7ed

test:
  secret_key_base:
  4b6bc79187c4bad384c3908e5d5217064ab20627cbd57747b7be9acb559d1f252d1cb98bb833cb8b3b136b0c8b7adb64bcca4b90b9fa7a48e8b8b7b6fb131644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base:
  5c1989ff4abf71e082f5adb2b187376fd358ac77a31c965b441848f73457ea322faad2e5d9a38004c1290dfe8d773530801315a46a173a0a6fae6d298f650d95
